import logging
from typing import Optional

import boto3
from botocore.exceptions import ClientError
from sqlalchemy.orm import Session

from app.core.config import settings
from app.models.email_log import EmailLog

logger = logging.getLogger(__name__)


class EmailService:
    def __init__(self):
        self.enabled = bool(settings.AWS_ACCESS_KEY_ID and settings.AWS_SECRET_ACCESS_KEY)
        if self.enabled:
            self._client = boto3.client(
                "ses",
                region_name=settings.AWS_REGION,
                aws_access_key_id=settings.AWS_ACCESS_KEY_ID,
                aws_secret_access_key=settings.AWS_SECRET_ACCESS_KEY,
            )
        else:
            logger.warning("Email service running in log-only mode (no AWS credentials)")

    def send_email(
        self,
        db: Session,
        to_email: str,
        subject: str,
        body_text: str,
        body_html: Optional[str] = None,
    ) -> bool:
        if not self.enabled:
            logger.info(f"[DEV] Email to={to_email} subject={subject}")
            self._log(db, to_email, subject, "dev_logged")
            return True

        try:
            body = {"Text": {"Data": body_text, "Charset": "UTF-8"}}
            if body_html:
                body["Html"] = {"Data": body_html, "Charset": "UTF-8"}

            self._client.send_email(
                Source=settings.SES_SENDER_EMAIL,
                ReplyToAddresses=[settings.SES_REPLY_TO_EMAIL],
                Destination={"ToAddresses": [to_email]},
                Message={
                    "Subject": {"Data": subject, "Charset": "UTF-8"},
                    "Body": body,
                },
            )
            logger.info(f"Email sent to {to_email}")
            self._log(db, to_email, subject, "sent")
            return True
        except ClientError as e:
            error_msg = str(e)
            logger.error(f"Failed to send email to {to_email}: {error_msg}")
            self._log(db, to_email, subject, "failed", error_msg)
            return False

    def send_analysis_report(
        self,
        db: Session,
        to_email: str,
        contract_title: str,
        risk_score: int,
        total_issues: int,
        summary: str,
        findings_by_severity: dict,
    ) -> bool:
        subject = f"Contract Analysis Report: {contract_title}"

        body_text = (
            f"Contract Analysis Report\n"
            f"========================\n\n"
            f"Contract: {contract_title}\n"
            f"Risk Score: {risk_score}/100\n"
            f"Total Issues Found: {total_issues}\n"
            f"  - High: {findings_by_severity.get('high', 0)}\n"
            f"  - Medium: {findings_by_severity.get('medium', 0)}\n"
            f"  - Low: {findings_by_severity.get('low', 0)}\n\n"
            f"Summary:\n{summary}\n"
        )

        body_html = f"""
        <html>
        <body style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <h2 style="color: #1a1a2e;">Contract Analysis Report</h2>
            <div style="background: #f5f5f5; padding: 16px; border-radius: 8px; margin-bottom: 16px;">
                <h3 style="margin-top: 0;">{contract_title}</h3>
                <div style="display: flex; gap: 16px;">
                    <div>
                        <span style="font-size: 32px; font-weight: bold; color: {'#e74c3c' if risk_score >= 70 else '#f39c12' if risk_score >= 40 else '#27ae60'};">
                            {risk_score}
                        </span>
                        <span style="color: #666;">/100 Risk Score</span>
                    </div>
                </div>
            </div>
            <div style="margin-bottom: 16px;">
                <h4>Issues Found: {total_issues}</h4>
                <ul>
                    <li><span style="color: #e74c3c;">High:</span> {findings_by_severity.get('high', 0)}</li>
                    <li><span style="color: #f39c12;">Medium:</span> {findings_by_severity.get('medium', 0)}</li>
                    <li><span style="color: #27ae60;">Low:</span> {findings_by_severity.get('low', 0)}</li>
                </ul>
            </div>
            <div>
                <h4>Summary</h4>
                <p>{summary}</p>
            </div>
            <hr style="border: 1px solid #eee; margin-top: 24px;">
            <p style="color: #999; font-size: 12px;">Generated by Contract Dispute Analyzer</p>
        </body>
        </html>
        """

        return self.send_email(db, to_email, subject, body_text, body_html)

    def _log(
        self,
        db: Session,
        to_email: str,
        subject: str,
        status: str,
        error_message: Optional[str] = None,
    ):
        log_entry = EmailLog(
            to_email=to_email,
            subject=subject,
            status=status,
            error_message=error_message,
        )
        db.add(log_entry)
        db.commit()


email_service = EmailService()
